In [1]:
import sys
sys.path.append("../src")

In [2]:
from data_prep import (
    load_data,
    build_model_dataset
)

In [3]:
courses, teachers, transactions = load_data()

In [4]:
model_df = build_model_dataset(
    courses,
    teachers,
    transactions
)

model_df.head()

,CourseID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating,TeacherID,EnrollmentCount,TotalRevenue,AvgRevenue,UniqueStudents,Expertise,YearsOfExperience,TeacherRating
0,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.00,4.74,TC00001,164,77453.92,472.28,164,Cybersecurity,6,3.24
1,CR00002,Java Programming,Programming,Free,Intermediate,0.00,37.70,2.43,TC00002,149,0.00,0.00,149,Digital Marketing,9,4.14
2,CR00003,C++ for Beginners,Programming,Free,Beginner,0.00,19.53,3.85,TC00003,173,0.00,0.00,173,Design,4,1.56
3,CR00004,Advanced Python,Programming,Free,Beginner,0.00,45.13,2.88,TC00004,154,0.00,0.00,154,Machine Learning,9,4.39
4,CR00005,Full Stack Development,Programming,Free,Beginner,0.00,28.68,1.28,TC00005,166,0.00,0.00,166,Finance,2,3.11

In [5]:
print(model_df.shape)
model_df.info()

(60, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CourseID           60 non-null     object
 1   CourseName         60 non-null     object
 2   CourseCategory     60 non-null     object
 3   CourseType         60 non-null     object
 4   CourseLevel        60 non-null     object
 5   CoursePrice        60 non-null     float64
 6   CourseDuration     60 non-null     float64
 7   CourseRating       60 non-null     float64
 8   TeacherID          60 non-null     object
 9   EnrollmentCount    60 non-null     int64
 10  TotalRevenue       60 non-null     float64
 11  AvgRevenue         60 non-null     float64
 12  UniqueStudents     60 non-null     int64
 13  Expertise          60 non-null     object
 14  YearsOfExperience  60 non-null     int64
 15  TeacherRating      60 non-null     float64
dtypes: float64(6), int64(3), object(7)
memory usage: 7.6+ KB

In [6]:
model_df.describe()

,CoursePrice,CourseDuration,CourseRating,EnrollmentCount,TotalRevenue,AvgRevenue,UniqueStudents,YearsOfExperience,TeacherRating
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,92.986333,27.632500,3.097833,166.666667,15188.724500,92.986333,166.666667,6.283333,3.125000
std,153.601506,16.092578,1.171232,12.523424,25409.721911,153.601506,12.523424,4.715972,0.949797
min,0.000000,1.200000,1.130000,140.000000,0.000000,0.000000,140.000000,1.000000,1.050000
25%,0.000000,14.500000,2.107500,157.500000,0.000000,0.000000,157.500000,3.000000,2.487500
50%,0.000000,28.505000,3.065000,166.000000,0.000000,0.000000,166.000000,6.000000,3.275000
75%,133.615000,43.012500,4.102500,174.750000,20858.060000,133.615000,174.750000,8.000000,3.827500
max,490.900000,49.730000,4.940000,196.000000,85416.600000,490.900000,196.000000,24.000000,4.970000

In [7]:
model_df.to_csv(
    "../data/model_dataset.csv",
    index=False
)

print("Saved successfully")

Saved successfully